version: "3.9"
services:
  algafood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "toor123"
    ports:
      - "3306:3306"
    networks:
      - algafood-network
  algafood-api:
    image: vaniltonalv3sfilho/algafood-api
    command: ["/app/wait-for-it.sh", "algafood-mysql:3306", "-t", "30", "--", "java", "-jar", "api.jar"]
    environment:
      DB_HOST: algafood-mysql
      SPRING_SESSION_STORE_TYPE: redis
      SPRING_REDIS_HOST: algafood-redis
      SPRING_PROFILES_ACTIVE: development
#    ports:
#      - "8080:8080"
    networks:
      - algafood-network
    depends_on:
      - algafood-mysql
#    deploy:
#      replicas: 3
  algafood-proxy:
    build: nginx/
    image: algafood-proxy
    ports:
      - "80:80"
    networks:
      - algafood-network
    depends_on:
      - algafood-api
  algafood-redis:
    image: redis:6.2.1-alpine
    networks:
      - algafood-network
networks:
  algafood-network:
    driver: bridge
